framework:
    secret: '%env(APP_SECRET)%'
    session:
        name: blog
#        cookie_path: 'http://localhost:8001/'
        handler_id: 'session.handler.native_file'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/build/manifest.json'
