version: '3'
services:
  purple_clouds_blog_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    links:
      - purple_clouds_blog_postgres
    volumes:
      - .:/var/www/html
    networks: ["default", "purple_clouds_network"]

  purple_clouds_blog_nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    depends_on:
      - purple_clouds_blog_php
    links:
      - purple_clouds_blog_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

  purple_clouds_blog_postgres:
    image: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}
