version: '3'
services:
  blog_purple_clouds_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    volumes:
      - .:/var/www/html
    depends_on:
      - blog_purple_clouds_mongo
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    depends_on:
      - blog_purple_clouds_php
    links:
      - blog_purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrrobot
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_assets:
    image: nginx:latest
    ports:
      - 8900:8900
    volumes:
      - ./public:/static
      - ./docker/assets/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
