version: '3'
services:
  blog_purple_clouds_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    volumes:
      - .:/var/www/html
    depends_on:
      - blog_purple_clouds_mongo
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_nginx:
    image: "bitnami/nginx:latest"
    ports:
      - "8001:8001"
    depends_on:
      - blog_purple_clouds_assets
      - blog_purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_mongo:
    image: "mongo:latest"
    restart: always
    volumes:
      - ./docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrrobot
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: ["purple_clouds_network_internal"]

  blog_purple_clouds_assets:
    build:
      context: .
      dockerfile: ./docker/assets/Dockerfile
    ports:
      - "8900:8900"
    volumes:
      - ./public/assets:/static/assets
      - ./public/uploads:/static/assets/uploads
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
