index:
  path: /
  controller: App\Controller\HomepageController::index

dashboard:
  path: /dashboard
  controller: App\Controller\BlogAdminController:dashboard

dashboard_login:
  path: /login
  controller: App\Controller\BlogAdminController:login

handle_code:
  path: /oauth/v2/code
  controller: App\Controller\BlogAdminController:handleCode

blog_logout:
  path: /logout
  methods: ['GET']

#POST INSERT
blog_post_insert:
  path: /dashboard/posts
  methods: ['POST', 'GET']
  controller: App\Controller\PostController:insert

articles:
  path: /articles

about_me:
  path: /about

blog_post:
  path: /posts/{slug}
  methods: ['GET']
  controller: App\Controller\PostController:showPost

blog_post_image_upload:
  path: /dashboard/posts/upload
  methods: ['POST']
  controller: App\Controller\PostController::upload

#Tags
tags:
  path: /dashboard/tags
  methods: ['GET']
  controller: App\Controller\BlogAdminController:tags

blog_tags_create:
  path: /api/v1/tags
  methods: ['POST']
  controller: App\Controller\TagController::insert
