index:
  path: /
  controller: App\Controller\HomepageController::index

dashboard:
  path: /dashboard
  controller: App\Controller\Admin\BlogAdminController:dashboard

dashboard_login:
  path: /login
  controller: App\Controller\Admin\BlogAdminController:login

handle_code:
  path: /oauth/v2/code
  controller: App\Controller\Admin\BlogAdminController:handleCode

blog_logout:
  path: /logout
  methods: ['GET']

articles:
  path: /articles

about_me:
  path: /about

#POSTS ADMIN
posts:
  path: /dashboard/posts
  methods: ['GET']
  controller: App\Controller\Admin\BlogAdminController:posts

posts_create:
  path: /dashboard/posts/create
  methods: ['GET']
  controller: App\Controller\Admin\BlogAdminController:postsCreate

posts_update:
  path: /dashboard/posts/{uuid}/update
  methods: ['GET']
  controller: App\Controller\Admin\BlogAdminController:handlePostUpdate

#POSTS API
blogs_posts_find_all:
  path: /api/v1/posts
  methods: ['GET']
  controller: App\Controller\Api\PostController:findAll

blog_posts_create:
  path: /api/v1/posts
  methods: ['POST']
  controller: App\Controller\Admin\BlogAdminController:handlePostCreate

# IN FUTURE THIS WILL BE IN API BUT FOR NOW CASAUL SYMFONY CREATE
#blog_posts_create:
#  path: /api/v1/posts
#  methods: ['POST']
#  controller: App\Controller\Api\PostController:create

blog_posts_update:
  path: /api/v1/posts/{uuid}
  methods: ['PATCH']
  controller: App\Controller\Api\PostController:update

blog_posts_find_one_by_uuid:
  path: /api/v1/posts/{uuid}
  methods: ['GET']
  controller: App\Controller\Api\PostController:findByUuid

blog_post_image_upload:
  path: /api/v1/posts/upload
  methods: ['POST']
  controller: App\Controller\Api\PostController::upload

#POSTS BLOG
blog_post:
  path: /posts/{slug}
  methods: ['GET']
  controller: App\Controller\PostController:findBySlug

#Tags
tags:
  path: /dashboard/tags
  methods: ['GET']
  controller: App\Controller\Admin\BlogAdminController:tags

blog_tags_find_all:
  path: /api/v1/tags
  methods: ['GET']
  controller: App\Controller\Api\TagController::findAll

blog_tags_create:
  path: /api/v1/tags
  methods: ['POST']
  controller: App\Controller\Api\TagController::create

#Categories
categories:
  path: /dashboard/categories
  methods: ['GET']
  controller: App\Controller\Admin\BlogAdminController:categories

blog_categories_find_all:
  path: /api/v1/categories
  methods: ['GET']
  controller: App\Controller\Api\CategoryController::findAll

blog_categories_create:
  path: /api/v1/categories
  methods: ['POST']
  controller: App\Controller\Api\CategoryController::create